// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_vtZ3JVU3CdH2QPkdLQ4VnmLdVASHmmI',
    appId: '1:1053666873304:android:e7d52763ab4635f0f86cad',
    messagingSenderId: '1053666873304',
    projectId: 'moodgenie-4fc46',
    storageBucket: 'moodgenie-4fc46.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYjI6qukGtNtg5lqPnhIEQAnhl2JIz3Vk',
    appId: '1:1053666873304:web:b77b51f1203d4e8ff86cad',
    messagingSenderId: '1053666873304',
    projectId: 'moodgenie-4fc46',
    authDomain: 'moodgenie-4fc46.firebaseapp.com',
    storageBucket: 'moodgenie-4fc46.firebasestorage.app',
    measurementId: 'G-DR5HZJG8P8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWqpRjabw-HN4hEzgKSrIDyYEXkfoyCHU',
    appId: '1:1053666873304:ios:009b14a45370078df86cad',
    messagingSenderId: '1053666873304',
    projectId: 'moodgenie-4fc46',
    storageBucket: 'moodgenie-4fc46.firebasestorage.app',
    iosBundleId: 'com.example.moodgenie',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWqpRjabw-HN4hEzgKSrIDyYEXkfoyCHU',
    appId: '1:1053666873304:ios:009b14a45370078df86cad',
    messagingSenderId: '1053666873304',
    projectId: 'moodgenie-4fc46',
    storageBucket: 'moodgenie-4fc46.firebasestorage.app',
    iosBundleId: 'com.example.moodgenie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYjI6qukGtNtg5lqPnhIEQAnhl2JIz3Vk',
    appId: '1:1053666873304:web:7fb6e46e6d411a40f86cad',
    messagingSenderId: '1053666873304',
    projectId: 'moodgenie-4fc46',
    authDomain: 'moodgenie-4fc46.firebaseapp.com',
    storageBucket: 'moodgenie-4fc46.firebasestorage.app',
    measurementId: 'G-DEDWFHYCS7',
  );

}